// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/google/wire"
	grpc2 "google.golang.org/grpc"
	"inventory/pkg/db"
	"inventory/pkg/grpc"
	"inventory/pkg/service"
	"shared/pkg/proto/inventory/v1"
)

// Injectors from di.go:

// Главная функция инъекции
func InitializeContainer(ctx context.Context, cfg *Config, initIndexes bool) (*Container, func(), error) {
	dbDB, err := ProvideMongoDB(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	repository := db.NewRepository(dbDB)
	serviceService := service.NewService(repository)
	api := grpc.New(serviceService)
	v := ProvideGRPCServerOptions()
	server := grpc2.NewServer(v...)
	container := &Container{
		inventoryApi:     api,
		inventoryService: serviceService,
		repository:       repository,
		Server:           server,
		DB:               dbDB,
	}
	return container, func() {
	}, nil
}

// di.go:

type Container struct {
	inventoryApi     *grpc.Api
	inventoryService service.InventoryService
	repository       *db.Repository
	Server           *grpc2.Server
	DB               *db.DB
}

func ProvideGRPCServerOptions() []grpc2.ServerOption {
	return []grpc2.ServerOption{}
}

func ProvideMongoDB(ctx context.Context, cfg *Config) (*db.DB, error) {
	return db.NewDB(ctx, cfg.MongoURI, cfg.MongoDB)
}

func InitializeDBIndexes(ctx context.Context, db2 *db.DB, initIndexes bool) error {
	return db2.InitIndex(ctx, initIndexes)
}

var DatabaseSet = wire.NewSet(
	ProvideMongoDB, db.NewRepository, wire.Bind(new(db.InventoryRepository), new(*db.Repository)), InitializeDBIndexes,
)

var ServiceSet = wire.NewSet(service.NewService, wire.Bind(new(service.InventoryService), new(*service.Service)))

var GRPCServerSet = wire.NewSet(
	ProvideGRPCServerOptions, grpc2.NewServer,
)

var APISet = wire.NewSet(grpc.New)

func (c *Container) RegisterGRPCServices() {
	inventory_v1.RegisterInventoryServiceServer(c.Server, c.inventoryApi)
}
