// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	"order/pkg/service"

	mock "github.com/stretchr/testify/mock"

	pkgmodel "inventory/pkg/db"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, order, newParts
func (_m *OrderService) CreateOrder(ctx context.Context, order *service.Order, newParts []*pkgmodel.Part) error {
	ret := _m.Called(ctx, order, newParts)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.Order, []*pkgmodel.Part) error); ok {
		r0 = rf(ctx, order, newParts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrder provides a mock function with given fields: orderUuid
func (_m *OrderService) GetOrder(orderUuid string) (*service.Order, error) {
	ret := _m.Called(orderUuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *service.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*service.Order, error)); ok {
		return rf(orderUuid)
	}
	if rf, ok := ret.Get(0).(func(string) *service.Order); ok {
		r0 = rf(orderUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orderUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: orderUuid, transactionUuid, status, paymentMethod
func (_m *OrderService) UpdateOrder(orderUuid string, transactionUuid *string, status *service.OrderStatus, paymentMethod *service.OrderPaymentMethod) error {
	ret := _m.Called(orderUuid, transactionUuid, status, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *string, *service.OrderStatus, *service.OrderPaymentMethod) error); ok {
		r0 = rf(orderUuid, transactionUuid, status, paymentMethod)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
