// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	"order/pkg/db"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: order
func (_m *OrderRepository) CreateOrder(order *db.Order) {
	_m.Called(order)
}

// GetOrder provides a mock function with given fields: orderUuid
func (_m *OrderRepository) GetOrder(orderUuid string) (*db.Order, error) {
	ret := _m.Called(orderUuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *db.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*db.Order, error)); ok {
		return rf(orderUuid)
	}
	if rf, ok := ret.Get(0).(func(string) *db.Order); ok {
		r0 = rf(orderUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orderUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: orderUuid, transactionUuid, status, paymentMethod
func (_m *OrderRepository) UpdateOrder(orderUuid string, transactionUuid *string, status *db.OrderStatus, paymentMethod *db.OrderPaymentMethod) error {
	ret := _m.Called(orderUuid, transactionUuid, status, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *string, *db.OrderStatus, *db.OrderPaymentMethod) error); ok {
		r0 = rf(orderUuid, transactionUuid, status, paymentMethod)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
