// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventory_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Категория
type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0 // Неизвестная категория
	Category_CATEGORY_ENGINE      Category = 1 // Двигатель
	Category_CATEGORY_FUEL        Category = 2 // Топливо
	Category_CATEGORY_PORTHOLE    Category = 3 // Иллюминатор
	Category_CATEGORY_WING        Category = 4 // Крыло
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_ENGINE",
		2: "CATEGORY_FUEL",
		3: "CATEGORY_PORTHOLE",
		4: "CATEGORY_WING",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"CATEGORY_ENGINE":      1,
		"CATEGORY_FUEL":        2,
		"CATEGORY_PORTHOLE":    3,
		"CATEGORY_WING":        4,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// Структура Part
type Part struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// Уникальный идентификатор детали
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Название детали
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Описание детали
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Цена за единицу
	Price float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	// Количество на складе
	StockQuantity int64 `protobuf:"varint,6,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	// Категория
	Category Category `protobuf:"varint,7,opt,name=category,proto3,enum=inventory.v1.Category" json:"category,omitempty"`
	// Размеры детали
	Dimensions *Dimensions `protobuf:"bytes,8,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	// Информация о производителе
	Manufacturer *Manufacturer `protobuf:"bytes,9,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// Теги для быстрого поиска
	Tags []string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	// Гибкие метаданные
	Metadata map[string]*Value `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Дата создания
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Дата обновления
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *Part) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Part) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Part) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Part) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Part) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Part) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *Part) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Part) GetManufacturer() *Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *Part) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Part) GetMetadata() map[string]*Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Part) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Part) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Размеры детали
type Dimensions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Длина в см
	Length *wrapperspb.DoubleValue `protobuf:"bytes,1,opt,name=length,proto3" json:"length,omitempty"`
	// Ширина в см
	Width *wrapperspb.DoubleValue `protobuf:"bytes,2,opt,name=width,proto3" json:"width,omitempty"`
	// Высота в см
	Height *wrapperspb.DoubleValue `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	// Вес в кг
	Weight        *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimensions) Reset() {
	*x = Dimensions{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimensions) ProtoMessage() {}

func (x *Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimensions.ProtoReflect.Descriptor instead.
func (*Dimensions) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Dimensions) GetLength() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Length
	}
	return nil
}

func (x *Dimensions) GetWidth() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Width
	}
	return nil
}

func (x *Dimensions) GetHeight() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *Dimensions) GetWeight() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Weight
	}
	return nil
}

// Информация о производителе
type Manufacturer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Страна производства
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// Сайт производителя
	Website       string `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacturer) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Manufacturer) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

// Гибкие метаданные
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MetaValue:
	//
	//	*Value_StringValue
	//	*Value_Int64Value
	//	*Value_DoubleValue
	//	*Value_BoolValue
	MetaValue     isValue_MetaValue `protobuf_oneof:"meta_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetMetaValue() isValue_MetaValue {
	if x != nil {
		return x.MetaValue
	}
	return nil
}

func (x *Value) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		if x, ok := x.MetaValue.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return nil
}

func (x *Value) GetInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		if x, ok := x.MetaValue.(*Value_Int64Value); ok {
			return x.Int64Value
		}
	}
	return nil
}

func (x *Value) GetDoubleValue() *wrapperspb.DoubleValue {
	if x != nil {
		if x, ok := x.MetaValue.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return nil
}

func (x *Value) GetBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		if x, ok := x.MetaValue.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return nil
}

type isValue_MetaValue interface {
	isValue_MetaValue()
}

type Value_StringValue struct {
	StringValue *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value *wrapperspb.Int64Value `protobuf:"bytes,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue *wrapperspb.DoubleValue `protobuf:"bytes,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue *wrapperspb.BoolValue `protobuf:"bytes,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_MetaValue() {}

func (*Value_Int64Value) isValue_MetaValue() {}

func (*Value_DoubleValue) isValue_MetaValue() {}

func (*Value_BoolValue) isValue_MetaValue() {}

// Фильтр по деталям
type PartsFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список UUID'ов
	Uuids []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	// Список имён
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	// Список категорий
	Categories []Category `protobuf:"varint,3,rep,packed,name=categories,proto3,enum=inventory.v1.Category" json:"categories,omitempty"`
	// Список стран производителей
	ManufacturerCountries []string `protobuf:"bytes,4,rep,name=manufacturer_countries,json=manufacturerCountries,proto3" json:"manufacturer_countries,omitempty"`
	// Список тегов
	Tags          []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartsFilter) Reset() {
	*x = PartsFilter{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartsFilter) ProtoMessage() {}

func (x *PartsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartsFilter.ProtoReflect.Descriptor instead.
func (*PartsFilter) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *PartsFilter) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *PartsFilter) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PartsFilter) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *PartsFilter) GetManufacturerCountries() []string {
	if x != nil {
		return x.ManufacturerCountries
	}
	return nil
}

func (x *PartsFilter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// GetPartRequest запрос на получение информации о детали по её UUID
type GetPartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор детали
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartRequest) Reset() {
	*x = GetPartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartRequest) ProtoMessage() {}

func (x *GetPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartRequest.ProtoReflect.Descriptor instead.
func (*GetPartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *GetPartRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// GetPartResponse ответ с информацией о детали
type GetPartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация о детали
	Part          *Part `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartResponse) Reset() {
	*x = GetPartResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartResponse) ProtoMessage() {}

func (x *GetPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartResponse.ProtoReflect.Descriptor instead.
func (*GetPartResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *GetPartResponse) GetPart() *Part {
	if x != nil {
		return x.Part
	}
	return nil
}

// GetListPartsRequest запрос на получение деталей с возможностью фильтрации
type GetListPartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Фильтр по деталям
	Filter        *PartsFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListPartsRequest) Reset() {
	*x = GetListPartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPartsRequest) ProtoMessage() {}

func (x *GetListPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPartsRequest.ProtoReflect.Descriptor instead.
func (*GetListPartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *GetListPartsRequest) GetFilter() *PartsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// GetListPartsResponse ответ с информацией о деталях
type GetListPartsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список найденных деталей
	Parts         []*Part `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListPartsResponse) Reset() {
	*x = GetListPartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPartsResponse) ProtoMessage() {}

func (x *GetListPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPartsResponse.ProtoReflect.Descriptor instead.
func (*GetListPartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *GetListPartsResponse) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x92\x05\n" +
	"\x04Part\x12;\n" +
	"\vobserved_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x06 \x01(\x03R\rstockQuantity\x122\n" +
	"\bcategory\x18\a \x01(\x0e2\x16.inventory.v1.CategoryR\bcategory\x128\n" +
	"\n" +
	"dimensions\x18\b \x01(\v2\x18.inventory.v1.DimensionsR\n" +
	"dimensions\x12>\n" +
	"\fmanufacturer\x18\t \x01(\v2\x1a.inventory.v1.ManufacturerR\fmanufacturer\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12<\n" +
	"\bmetadata\x18\v \x03(\v2 .inventory.v1.Part.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aP\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.inventory.v1.ValueR\x05value:\x028\x01\"\xe2\x01\n" +
	"\n" +
	"Dimensions\x124\n" +
	"\x06length\x18\x01 \x01(\v2\x1c.google.protobuf.DoubleValueR\x06length\x122\n" +
	"\x05width\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05width\x124\n" +
	"\x06height\x18\x03 \x01(\v2\x1c.google.protobuf.DoubleValueR\x06height\x124\n" +
	"\x06weight\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\x06weight\"V\n" +
	"\fManufacturer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\"\x98\x02\n" +
	"\x05Value\x12A\n" +
	"\fstring_value\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\vstringValue\x12>\n" +
	"\vint64_value\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueH\x00R\n" +
	"int64Value\x12A\n" +
	"\fdouble_value\x18\x03 \x01(\v2\x1c.google.protobuf.DoubleValueH\x00R\vdoubleValue\x12;\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueH\x00R\tboolValueB\f\n" +
	"\n" +
	"meta_value\"\xbc\x01\n" +
	"\vPartsFilter\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x126\n" +
	"\n" +
	"categories\x18\x03 \x03(\x0e2\x16.inventory.v1.CategoryR\n" +
	"categories\x125\n" +
	"\x16manufacturer_countries\x18\x04 \x03(\tR\x15manufacturerCountries\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"$\n" +
	"\x0eGetPartRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"9\n" +
	"\x0fGetPartResponse\x12&\n" +
	"\x04part\x18\x01 \x01(\v2\x12.inventory.v1.PartR\x04part\"H\n" +
	"\x13GetListPartsRequest\x121\n" +
	"\x06filter\x18\x01 \x01(\v2\x19.inventory.v1.PartsFilterR\x06filter\"@\n" +
	"\x14GetListPartsResponse\x12(\n" +
	"\x05parts\x18\x01 \x03(\v2\x12.inventory.v1.PartR\x05parts*v\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCATEGORY_ENGINE\x10\x01\x12\x11\n" +
	"\rCATEGORY_FUEL\x10\x02\x12\x15\n" +
	"\x11CATEGORY_PORTHOLE\x10\x03\x12\x11\n" +
	"\rCATEGORY_WING\x10\x042\xb1\x01\n" +
	"\x10InventoryService\x12F\n" +
	"\aGetPart\x12\x1c.inventory.v1.GetPartRequest\x1a\x1d.inventory.v1.GetPartResponse\x12U\n" +
	"\fGetListParts\x12!.inventory.v1.GetListPartsRequest\x1a\".inventory.v1.GetListPartsResponseB&Z$/pkg/proto/inventory/v1;inventory_v1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(Category)(0),                  // 0: inventory.v1.Category
	(*Part)(nil),                   // 1: inventory.v1.Part
	(*Dimensions)(nil),             // 2: inventory.v1.Dimensions
	(*Manufacturer)(nil),           // 3: inventory.v1.Manufacturer
	(*Value)(nil),                  // 4: inventory.v1.Value
	(*PartsFilter)(nil),            // 5: inventory.v1.PartsFilter
	(*GetPartRequest)(nil),         // 6: inventory.v1.GetPartRequest
	(*GetPartResponse)(nil),        // 7: inventory.v1.GetPartResponse
	(*GetListPartsRequest)(nil),    // 8: inventory.v1.GetListPartsRequest
	(*GetListPartsResponse)(nil),   // 9: inventory.v1.GetListPartsResponse
	nil,                            // 10: inventory.v1.Part.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(*wrapperspb.DoubleValue)(nil), // 12: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil), // 13: google.protobuf.StringValue
	(*wrapperspb.Int64Value)(nil),  // 14: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),   // 15: google.protobuf.BoolValue
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	11, // 0: inventory.v1.Part.observed_at:type_name -> google.protobuf.Timestamp
	0,  // 1: inventory.v1.Part.category:type_name -> inventory.v1.Category
	2,  // 2: inventory.v1.Part.dimensions:type_name -> inventory.v1.Dimensions
	3,  // 3: inventory.v1.Part.manufacturer:type_name -> inventory.v1.Manufacturer
	10, // 4: inventory.v1.Part.metadata:type_name -> inventory.v1.Part.MetadataEntry
	11, // 5: inventory.v1.Part.created_at:type_name -> google.protobuf.Timestamp
	11, // 6: inventory.v1.Part.updated_at:type_name -> google.protobuf.Timestamp
	12, // 7: inventory.v1.Dimensions.length:type_name -> google.protobuf.DoubleValue
	12, // 8: inventory.v1.Dimensions.width:type_name -> google.protobuf.DoubleValue
	12, // 9: inventory.v1.Dimensions.height:type_name -> google.protobuf.DoubleValue
	12, // 10: inventory.v1.Dimensions.weight:type_name -> google.protobuf.DoubleValue
	13, // 11: inventory.v1.Value.string_value:type_name -> google.protobuf.StringValue
	14, // 12: inventory.v1.Value.int64_value:type_name -> google.protobuf.Int64Value
	12, // 13: inventory.v1.Value.double_value:type_name -> google.protobuf.DoubleValue
	15, // 14: inventory.v1.Value.bool_value:type_name -> google.protobuf.BoolValue
	0,  // 15: inventory.v1.PartsFilter.categories:type_name -> inventory.v1.Category
	1,  // 16: inventory.v1.GetPartResponse.part:type_name -> inventory.v1.Part
	5,  // 17: inventory.v1.GetListPartsRequest.filter:type_name -> inventory.v1.PartsFilter
	1,  // 18: inventory.v1.GetListPartsResponse.parts:type_name -> inventory.v1.Part
	4,  // 19: inventory.v1.Part.MetadataEntry.value:type_name -> inventory.v1.Value
	6,  // 20: inventory.v1.InventoryService.GetPart:input_type -> inventory.v1.GetPartRequest
	8,  // 21: inventory.v1.InventoryService.GetListParts:input_type -> inventory.v1.GetListPartsRequest
	7,  // 22: inventory.v1.InventoryService.GetPart:output_type -> inventory.v1.GetPartResponse
	9,  // 23: inventory.v1.InventoryService.GetListParts:output_type -> inventory.v1.GetListPartsResponse
	22, // [22:24] is the sub-list for method output_type
	20, // [20:22] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	file_inventory_v1_inventory_proto_msgTypes[3].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
